name: atec
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.8
  go_router: ^14.0.0
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.4
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  custom_lint: ^0.6.2
  build_runner: ^2.4.9
  riverpod_lint: ^2.3.9
  flutter_lints: ^3.0.2
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true

  assets:
   - assets/icons/
   - assets/fonts/lexend/
   - assets/images/